### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by larshp**

### CODE REVIEW

**Comment by sbcgua** [comment]
Thanks Lars ! =)

**Comment by sbcgua** [comment]
@larshp one off-topic question: do you occasionally know how to trigger unit test execution for a given object (program, class, package...)? Kind of `cl_abap_unit_test_run( 'zmy_pkg' )` (well, probably more lines of course) and it'd display the result like if I'd trigger it manually in IDE transactions.

**Comment by larshp** [comment]
via custom code? try taking a look at https://github.com/larshp/abapOpenTest/blob/master/src/runner/zcl_aot_runner.clas.abap#L204

**Comment by larshp** [comment]
video here: https://www.youtube.com/watch?v=UGHJnCczLGk

it runs all unit tests with full coverage, so its possible to tell which code is hit by a unit test, also code outside of the main class is tracked. So, yes, it is a bit like your idea, PRs welcome 😄

**Comment by sbcgua** [comment]
Abap CI :) Cool ! Very very interesting, thanks ! :+1:  
BTW does this work on below 7.4 (7.31 in particular) ?

**Comment by larshp** [comment]
¯\_(ツ)_/¯

but I dont think it will require lots of changes, if any

**Pull request merged**
